version: '3.7'

services:
  minio1:
    container_name: minio1
    restart: always
    image: minio/minio:RELEASE.2020-10-27T04-03-55Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    container_name: minio2
    restart: always
    image: minio/minio:RELEASE.2020-10-27T04-03-55Z
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    container_name: minio3
    restart: always
    image: minio/minio:RELEASE.2020-10-27T04-03-55Z
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    container_name: minio4
    restart: always
    image: minio/minio:RELEASE.2020-10-27T04-03-55Z
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./docker-conf/nginx/nginx.minio.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9005:9000
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:

