version: '3'
services:
  # 后端容器
  gin-web-stage:
    container_name: gin-web-stage
    restart: always
    # 本地构建使用build, 这里我在持续构建平台以及传到了阿里云镜像仓库, 因此直接使用镜像地址
    image: registry.cn-shenzhen.aliyuncs.com/piupuer/gin-web-stage:${WEB_STAGE_TAG}
    # build:
    #   # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
    #   context: ./gin-web
    #   dockerfile: Dockerfile.stage
    # 设置工作目录为容器内的app文件夹(容器运行时会用到)
    working_dir: /app/gin-web-stage
    environment:
      TZ: Asia/Shanghai
    volumes:
      # 映射容器产生的日志到主机的logs文件夹
      - app-logs-stage-data:/app/gin-web-stage/logs
      - app-conf-stage-data:/app/gin-web-stage/conf
    # 映射端口
    ports:
      # 程序运行端口/性能调试端口
      - 8080:8080
      - 8005:8005
    # 映射日志驱动
    logging:
      driver: loki
      options:
        # 日志推送地址
        loki-url: http://10.13.2.252:3100/api/prom/push
    depends_on:
      - gin-web-mysql-stage
      - gin-web-redis-stage
    links:
      # 为数据库设置别名, docker网桥名:应用内部访问名
      - gin-web-mysql-stage:docker-mysql
      - gin-web-redis-stage:docker-redis
    networks:
      - stage-net

networks:
  stage-net:

# 全局数据卷, 可容器间共享
volumes:
  app-logs-stage-data:
  app-conf-stage-data:
