version: '3'
services:
  # 前端容器
  gin-web-vue-stage:
    container_name: gin-web-vue-stage
    restart: always
    image: registry.cn-shenzhen.aliyuncs.com/piupuer/gin-web-vue-stage:${UI_STAGE_TAG}
    # build:
    #   context: ./gin-web-vue
    #   dockerfile: Dockerfile.stage
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8081:8081
    # 映射日志驱动
    logging:
      driver: loki
      options:
        # 日志推送地址
        loki-url: http://10.13.2.252:3100/api/prom/push
    links:
      # 为nginx配置后端访问别名, docker网桥名:应用内部访问名
      - gin-web-stage:docker-web
    # 挂载文件
    volumes:
      # 映射容器产生的日志到主机的logs文件夹
      - vue-logs-stage-data:/var/log/nginx
    # 设置网络
    networks:
      - stage-net

networks:
  stage-net:

# 全局数据卷, 可容器间共享
volumes:
  vue-logs-stage-data:
