version: '3'
services:
  # 数据库
  gin-web-mysql-stage:
    # 容器名称
    container_name: gin-web-mysql-stage
    # 重启策略: 容器退出时总是重启容器
    restart: always
    # 指定镜像, mysql 8.0
    image: mysql:8.0.19
    ports:
      # 避免端口冲突, 宿主机不用3306
      - 3306:3306
    # 映射日志驱动
    logging:
      driver: loki
      options:
        # 日志推送地址(可以改为你的域名或者配置到hosts文件中)
        loki-url: http://10.13.2.252:3100/api/prom/push
    # 设置环境变量
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gin_web_stage
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    # 自定义命令
    command:
      # utf8
      # 不区分大小写
      # mysql8.0需要设置原生密码, 否则可能无法登录
      # 增大数据包, 默认值1M
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
      --default-authentication-plugin=mysql_native_password
      --max_allowed_packet=128M
    # 挂载文件
    volumes:
      - mysql-stage-data:/var/lib/mysql
      - mysql-stage-conf:/etc/mysql/conf.d
    # 设置网络
    networks:
      - stage-net

  # 缓存
  gin-web-redis-stage:
    # 容器名称
    container_name: gin-web-redis-stage
    # 重启策略: 容器退出时总是重启容器
    restart: always
    # 指定镜像
    image: redis:6.0.3
    ports:
      - 6379:6379
    # 映射日志驱动
    logging:
      driver: loki
      options:
        # 日志推送地址
        loki-url: http://10.13.2.252:3100/api/prom/push
    environment:
      TZ: Asia/Shanghai
    # 挂载文件
    volumes:
      - redis-stage-data:/data
    # 设置网络
    networks:
      - stage-net

networks:
  stage-net:

# 全局数据卷, 可容器间共享
volumes:
  mysql-stage-data:
  mysql-stage-conf:
  redis-stage-data:
