version: '3'
services:
  # loki日志服务器(用于存储日志)
  loki:
    container_name: loki
    restart: always
    image: grafana/loki:1.6.1
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-config-data:/etc/loki
      - loki-data:/loki
    networks:
      - loki-net

  # promtail日志传输代理(用于传输日志)
  promtail:
    container_name: promtail
    restart: always
    image: grafana/promtail:1.6.1
    volumes:
      - promtail-data:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-net

  # grafana日志可视化工具(用于查找日志)
  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana:7.2.2
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - loki-net

networks:
  loki-net:

volumes:
  loki-config-data:
  loki-data:
  promtail-data:
  grafana-data:
